[build]
  base = "client"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  REACT_APP_API_URL = "https://aidiy-dev.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 